"""Naive baseline: keep every alert.

This represents the status-quo workflow at most banks today: every alert
generated by transaction monitoring rules ends up on a compliance analyst's
queue. The baseline guarantees 100% recall on true positives but at the cost
of 100% alert volume — i.e., no labour savings whatsoever.

We benchmark the LLM triage agent against this exact baseline.
"""
from __future__ import annotations

import pandas as pd


def baseline_decide(df: pd.DataFrame) -> pd.DataFrame:
    """Return the input frame with a `decision` column == 'keep' for all rows."""
    out = df.copy()
    out["decision"] = "keep"
    out["confidence"] = 1.0
    out["rationale"] = "naive_keep_all"
    return out


def baseline_label_kept(df: pd.DataFrame) -> pd.Series:
    """Return predicted-positive (kept) mask. All True for naive baseline."""
    return pd.Series([True] * len(df), index=df.index)
